# This is a dofile. For usage info visit https://github.com/roeldev/do

# setup project, get dependencies
setup: go get -v -t -d ./...

# run tests with coverage and race detection
test: |
  go test -race -cover -coverprofile=coverage.out -v ./...
  go tool cover -func=coverage.out

example1: go run -race ./examples/1_basic/main.go
example2: go run -race ./examples/2_wrap/main.go
example3: go run -race ./examples/3_wrap_existing/main.go
example4: go run -race ./examples/4_custom_error/main.go
